markdown: kramdown

dag_title: About Dagger
dag_content: Dagger is part of a new wave of Distributed Ledger projects based on a DAG infrastructure. DAG, or Directed acyclic graph, is an alternative method for sending data amongst people within a distributed, decentralized environment. This is done without a blockchain, allowing for greater scalability.

mine_title: Mining quick start
mine_content: The first mineable DAG. Follow the steps below. If you get stuck, join us in the discord.

wallet_title: Wallets
wallet_content: If you need help choosing the correct version, please open About your PC and look for system type, then select the appropriate release for your operating system below.

roadmap_title: Roadmap

team_title: XDAG team
devNum: 28

offical: FQglVQtb60vQv2DOWEUL7yh3smtj7g1s

baseurl: "/"

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

title: XDAG
description: A new DAG-based cryptocurrency
logo: /assets/images/logo.png

author:
  name: Xdag.io
  twitter: XDAG_Community
  email: communitymanager@xdag.io 

social:
  links:
    - https://t.me/dagger_cryptocurrency
    - https://www.facebook.com/XDAG.Dagger.Community/
    - https://twitter.com/XDAG_Community
    - https://discord.gg/YxXUVQJ
    - https://www.reddit.com/r/xdag/
    - https://github.com/orgs/XDagger

twitter:
  card: summary
  username: XDAG_Community

facebook:
  publisher: https://www.facebook.com/XDAG.Dagger.Community/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/default-card.png